### ISSUE TITLE
Some kudos

### ISSUE THREAD

**Issue by fatso83** [AntoineViau/webassembly-jpeg#1]
Just wanted to drop a note saying that this was really cool! So kudos for that. That being said, I think a few hours of investing in packing this up in a format ready for public consumption would make it a lot more accessible 😸 

The dream would of course be to just load the main (non-DOM) crunching parts of this script into a `WebWorker` and send buffers to that for it to work on. Already pretty close. 

Anyway, thanks a lot for the demo!

**Comment by AntoineViau** [comment]
Thanks a lot for the kudos ! That's good to read, I really appreciate you took the time...
That being said, I did what you asked : the project has been refactored for public comsumption with a proper readme.
