### ISSUE TITLE
Errors in the example

### ISSUE THREAD

**Issue by fatso83** [AntoineViau/webassembly-jpeg#2]
I followed the instructions step-by-step (even [made them scriptable for a repeatable process](https://github.com/fatso83/webassembly-jpeg/commit/b2c32b54e821fcf7c5de431271af4998dd884c6d)), but the example simple doesn't work:

```
example.js:1 wasm streaming compile failed: TypeError: Module.cwrap is not a function

(anonymous) @ example.js:1
Promise.catch (async)
doNativeWasm @ example.js:1
Module.asm @ example.js:1
(anonymous) @ example.js:1

falling back to ArrayBuffer instantiation
(anonymous) @ example.js:1
Promise.catch (async)
doNativeWasm @ example.js:1
Module.asm @ example.js:1
(anonymous) @ example.js:1
```

Fixed the missing `start` script, btw, so it should be possible to simply run `./install-linux.sh && npm start`.

**Comment by AntoineViau** [comment]
Fixed.
I don't really know why it was not working anymore. Some updates in emsdk ? Maybe I worked with an older version ?
Anyway, have a look at the diff. It should be working now.

**Comment by fatso83** [comment]
And it works! Thank you :-) This is a really nice demo.
