### ISSUE TITLE
does not hold exif and markers + some files would not decode / encode nicely and will have color issues

### ISSUE THREAD

**Issue by adibar** [AntoineViau/webassembly-jpeg#3]
![test](https://user-images.githubusercontent.com/4689827/38111331-389de6d8-33a7-11e8-8686-adf51d9a3f5b.jpg)

I have tried playing with the following function to allow using base image coefficient and to preserve exif and markers but could not succeed.

jpeg_write_coefficients(&cinfo, dst_coef_arrays);
jpeg_copy_critical_parameters(((j_decompress_ptr)(gIP->ip_SrcBuf)), &cinfo);
// to store exif and marker =>
jcopy_markers_execute( ((j_decompress_ptr)(gIP->ip_SrcBuf)), &cinfo, copyoption);

would it be a big hassle to add it? 
attached is and image with a shift in colors - probably due to the reasons above.

**Comment by AntoineViau** [comment]
Well, the purpose of this repo is to experiment with Web Assembly, not with the Jpeg library. I do not have time for that kind of work. Sorry I cannot help you.
