### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by timotheecour** [AntoineViau/webassembly-jpeg#4]
* after make install, 
`#include "libjpeg/jpeglib.h"`
should be:
`#include "jpeglib.h"`

* maybe suggest `git clone https://github.com/LuaDist/libjpeg` as (simpler) alternative to `Download the JPEG lib ... tar xvzf ...`

**Comment by AntoineViau** [comment]
About the #include : the readme gives step by step instructions to build the app in a directory. The JPEG lib is in a separate child directory. The idea is to build separatly the jpeg lib to keep concern separated.

About the "git clone" vs "direct download" : I made this choice to show you can get a strict C library from the provider web site and built it in your WASM target project straight away. But your idea is good with the JPEG Group git repo. But I did not look for it at the time.
